Add Cloudflare Pages link as PR comment
product-os/flowzone pull request #1109
Opened 2024-07-10 19:10 UTC by vipulgupta2048

It's annoying to find the CF pages link from inside the GHA run summary, lost of people have had this friction. 
No more. This PR adds that link to the comments. 

Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>

2024-07-11 10:28 UTC, vipulgupta2048 commented
Completed: https://github.com/product-os/flowzone/pull/1109#issuecomment-2221419322

2024-07-11 10:50 UTC, vipulgupta2048 commented
Completed: https://github.com/product-os/flowzone/pull/1109#issuecomment-2221419322

2024-07-11 15:07 UTC, ab77 requested changes
@vipulgupta2048 could you please just add a test so that we know the new step is working in the PR draft/sync stage (before merging). I think flowzone has a CF site already..

2024-07-12 13:08 UTC, klutchell commented
I see the test comment in this PR, it just got buried in the history. LGTM

2024-07-12 13:08 UTC, klutchell commented on flowzone.yml
> +        uses: peter-evans/find-comment@v3
Suggest pinning to the full semver here

2024-07-12 13:09 UTC, klutchell commented on flowzone.yml
> +        uses: peter-evans/create-or-update-comment@v4
Suggest pinning to the full semver here

2024-07-13 14:26 UTC, ab77 approved these changes

2024-07-13 15:12 UTC, merged